"""Generate the LaTeX tables from the data.

    python src/make_tables.py

Writes:

    tables/thematic_summary.tex   Table 1  - tasks by deployment-score tercile
    tables/onet_occupations.tex   Appendix A - occupations by sub-cluster
    tables/matched_providers.tex  providers selected as a best match

The tercile assignment and the occupation lists are computed from the data. Two
things are inputs rather than outputs:

  - The five category names per tercile in Table 1 were written from the prompt
    documented in the manuscript appendix, so they live in
    data/thematic_categories.csv. This script checks that each example task
    falls in the tercile the table assigns it to.
  - The provider table in the manuscript carries hand-written marketing-service
    descriptions that are not held in any data file here. What this script emits
    instead is the provider list the match selected, with task counts.
"""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import (
    DEPLOYMENT_THRESHOLD, ONET_TASKS, PROVIDER_TASKS, TABLES,
    THEMATIC_CATEGORIES, load_scored_tasks,
)


def _esc(s):
    """Escape the LaTeX specials that occur in this data."""
    return (
        str(s)
        .replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
    )


def table_thematic_summary():
    """Table 1, with the tercile membership of each example task verified."""
    df = load_scored_tasks()
    cats = pd.read_csv(THEMATIC_CATEGORIES)

    problems = []
    for _, r in cats.iterrows():
        stem = r["example_task"].rstrip(".")[:48]
        hit = df[df["Task"].str.startswith(stem, na=False)]
        if hit.empty:
            problems.append(f"example task not found in data: {stem!r}")
        elif r["tercile"] not in set(hit["tercile"].astype(str)):
            problems.append(
                f"{stem!r} is in {sorted(set(hit['tercile'].astype(str)))}, "
                f"table says {r['tercile']}"
            )

    sizes = df["tercile"].value_counts().to_dict()
    cuts = df["best_match_score"].quantile([0, 1 / 3, 2 / 3, 1]).round(4).tolist()

    rows = []
    for tercile in ("Top", "Middle", "Bottom"):
        block = cats[cats["tercile"] == tercile]
        for i, (_, r) in enumerate(block.iterrows()):
            label = f"{tercile} Tercile" if i == 0 else ""
            rows.append(
                f"{_esc(label)} & \\textbf{{{_esc(r['category'])}:}} "
                f"& {_esc(r['example_task'])} \\\\"
            )
        if tercile != "Bottom":
            rows.append(r"\midrule")

    tex = "\n".join([
        r"% Generated by src/make_tables.py - do not edit by hand.",
        f"% Tercile sizes: {sizes}. Score cutpoints: {cuts}.",
        r"\begin{table}[!htbp]",
        r"\caption{Thematic summary of tasks by deployment-score tercile}",
        r"\label{tab:thematic_sum}",
        r"\centering\footnotesize",
        r"\begin{tabular}{@{}p{0.10\textwidth} p{0.26\textwidth} p{0.56\textwidth}@{}}",
        r"\toprule",
        r"\textbf{Tercile} & \textbf{Category} & \textbf{Example Task from O*Net} \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ])
    (TABLES / "thematic_summary.tex").write_text(tex + "\n")
    return len(cats), problems, sizes, cuts


def table_onet_occupations():
    """Appendix A: the occupations in each sub-cluster, straight from O*NET."""
    onet = pd.read_csv(ONET_TASKS)
    rows = []
    for sub in sorted(onet["Sub-Cluster"].unique()):
        occs = sorted(onet[onet["Sub-Cluster"] == sub]["Occupation"].unique())
        rows.append(f"{_esc(sub)} &\n{_esc('; '.join(occs))} \\\\\n")

    tex = "\n".join([
        r"% Generated by src/make_tables.py - do not edit by hand.",
        f"% {onet['Occupation'].nunique()} occupations, {len(onet)} tasks.",
        r"\begin{table}[!htbp]",
        r"\caption{O*NET Database: Occupations in the Marketing and Sales Cluster}",
        r"\label{tab:onet}",
        r"\centering \footnotesize",
        r"\begin{tabularx}{\textwidth}{@{}L{0.33\textwidth} Y@{}}",
        r"\toprule",
        r"\textbf{Sub-cluster} & \textbf{Occupations} \\",
        r"\midrule",
        "\n".join(rows),
        r"\bottomrule",
        r"\end{tabularx}",
        r"\end{table}",
    ])
    (TABLES / "onet_occupations.tex").write_text(tex + "\n")
    return onet["Occupation"].nunique(), onet["Sub-Cluster"].nunique()


def table_matched_providers():
    """Appendix B, derived: the providers the match actually selected.

    Every best_match string appears verbatim in the provider corpus, so each
    scored task can be traced back to the service that supplied its match.
    """
    scored = load_scored_tasks()
    corpus = pd.read_csv(PROVIDER_TASKS)
    lookup = corpus.drop_duplicates("task_involved").set_index("task_involved")[
        "service_name"
    ]
    scored["matched_service"] = scored["best_match"].map(lookup)

    untraced = int(scored["matched_service"].isna().sum())
    counts = scored["matched_service"].value_counts()
    above = (
        scored[scored["best_match_score"] >= DEPLOYMENT_THRESHOLD]["matched_service"]
        .value_counts()
        .reindex(counts.index)
        .fillna(0)
        .astype(int)
    )

    rows = [
        f"{_esc(svc)} & {n} & {above[svc]} \\\\" for svc, n in counts.items()
    ]
    tex = "\n".join([
        r"% Generated by src/make_tables.py - do not edit by hand.",
        f"% Corpus: {corpus['service_name'].nunique()} services / {len(corpus)} "
        f"task descriptions. Selected as a best match: {len(counts)}.",
        r"\begin{table}[!htbp]",
        r"\caption{Providers selected as a best match, with task counts}",
        r"\label{tab:matched_providers}",
        r"\centering \footnotesize",
        r"\begin{tabular}{@{}lrr@{}}",
        r"\toprule",
        r"\textbf{Provider or service} & \textbf{Tasks matched} & "
        r"\textbf{Above cutoff} \\",
        r"\midrule",
        *rows,
        r"\midrule",
        f"\\textbf{{Total}} & {int(counts.sum())} & {int(above.sum())} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ])
    (TABLES / "matched_providers.tex").write_text(tex + "\n")
    return corpus["service_name"].nunique(), len(counts), untraced


def main():
    TABLES.mkdir(exist_ok=True)

    n_cat, problems, sizes, cuts = table_thematic_summary()
    print(f"  wrote tables/thematic_summary.tex  ({n_cat} categories)")
    print(f"    tercile sizes {sizes}, cutpoints {cuts}")
    if problems:
        print("    WARNING: example tasks disagree with the data:")
        for p in problems:
            print(f"      - {p}")
    else:
        print("    all example tasks verified to fall in their stated tercile")

    n_occ, n_sub = table_onet_occupations()
    print(f"  wrote tables/onet_occupations.tex  ({n_occ} occupations, {n_sub} sub-clusters)")

    n_corpus, n_sel, untraced = table_matched_providers()
    print(f"  wrote tables/matched_providers.tex  ({n_sel} of {n_corpus} services selected)")
    if untraced:
        print(f"    WARNING: {untraced} tasks could not be traced to a service")


if __name__ == "__main__":
    main()
